"use client";

import { useMemo, useState } from "react";

type Account = { id: string; userId: string; email: string; displayName: string; role: "driver" | "hotel"; status: "pending" | "active" | "suspended" };
type PropertyRow = { property: { id: string; name: string; destination: string; city: string }; member: { id: string; userId: string; role: "owner" | "manager" } | null; account: { displayName: string; email: string } | null };
async function api<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, { ...init, headers: { "content-type": "application/json", ...init?.headers } }); const data = await response.json() as T & { error?: string }; if (!response.ok) throw new Error(data.error ?? "Request failed."); return data; }

export function AdminAccessManager({ initialAccounts, initialProperties, initialMessage = "" }: { initialAccounts: Account[]; initialProperties: PropertyRow[]; initialMessage?: string }) {
  const [accounts, setAccounts] = useState<Account[]>(initialAccounts); const [properties, setProperties] = useState<PropertyRow[]>(initialProperties); const [message, setMessage] = useState(initialMessage);
  const [propertyName, setPropertyName] = useState(""); const [destination, setDestination] = useState(""); const [city, setCity] = useState(""); const [propertyId, setPropertyId] = useState(""); const [accountId, setAccountId] = useState("");
  const load = async () => { try { const [accountData, propertyData] = await Promise.all([api<{ accounts: Account[] }>("/api/admin/operations-accounts"), api<{ properties: PropertyRow[] }>("/api/admin/hotels")]); setAccounts(accountData.accounts); setProperties(propertyData.properties); setMessage(""); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to load portal access."); } };
  const activeHotelAccounts = useMemo(() => accounts.filter(account => account.role === "hotel" && account.status === "active"), [accounts]);
  const updateStatus = async (id: string, status: "active" | "suspended") => { try { await api("/api/admin/operations-accounts", { method: "PATCH", body: JSON.stringify({ id, status }) }); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to update access."); } };
  const createProperty = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); try { await api("/api/admin/hotels", { method: "POST", body: JSON.stringify({ name: propertyName, destination, city }) }); setPropertyName(""); setDestination(""); setCity(""); await load(); setMessage("Hotel property created. Assign its approved partner below."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to create property."); } };
  const assign = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!propertyId || !accountId) return setMessage("Choose both a property and approved hotel partner."); try { await api(`/api/admin/hotels/${propertyId}/members`, { method: "POST", body: JSON.stringify({ operationsAccountId: accountId, role: "owner" }) }); await load(); setMessage("Hotel partner assigned. They can now view only this property’s data."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to assign property."); } };
  return <div className="admin-content"><section className="admin-panel"><div className="admin-panel-heading"><div><p className="eyebrow">Onboarding</p><h2>Portal access requests</h2></div><p>Approve drivers and hotel partners after their Google sign-in request. Access is stored in PostgreSQL, not in environment variables.</p></div>{message && <p className="operations-notice">{message}</p>}<div className="package-list">{accounts.map(account => <article key={account.id}><div><span>{account.role === "hotel" ? "Hotel partner" : "Driver"} · {account.status}</span><strong>{account.displayName}</strong><p>{account.email}</p></div><div>{account.status !== "active" && <button className="button button-primary" onClick={() => updateStatus(account.id, "active")}>Approve</button>}{account.status !== "suspended" && <button className="button button-secondary" onClick={() => updateStatus(account.id, "suspended")}>Suspend</button>}</div></article>)}{!accounts.length && !message && <p className="operations-notice">No portal access requests yet.</p>}</div></section><section className="admin-panel"><div className="admin-panel-heading"><div><p className="eyebrow">Hotel ownership</p><h2>Properties and partner assignments</h2></div><p>Partners see bookings and rooms only for properties assigned here.</p></div><div className="operations-manager"><form className="operations-form" onSubmit={createProperty}><label>Property name<input required value={propertyName} onChange={event => setPropertyName(event.target.value)} /></label><label>Destination<input required value={destination} onChange={event => setDestination(event.target.value)} /></label><label>City<input required value={city} onChange={event => setCity(event.target.value)} /></label><button className="button button-primary">Create property</button></form><form className="operations-form" onSubmit={assign}><label>Property<select required value={propertyId} onChange={event => setPropertyId(event.target.value)}><option value="">Select property</option>{properties.filter(row => row.member === null).map(row => <option key={row.property.id} value={row.property.id}>{row.property.name} · {row.property.city}</option>)}</select></label><label>Approved hotel partner<select required value={accountId} onChange={event => setAccountId(event.target.value)}><option value="">Select partner</option>{activeHotelAccounts.map(account => <option key={account.id} value={account.id}>{account.displayName} · {account.email}</option>)}</select></label><button className="button button-secondary">Assign owner</button></form></div><div className="package-list">{properties.map(({ property, member, account }) => <article key={member?.id ?? property.id}><div><span>{property.destination} · {property.city}</span><strong>{property.name}</strong><p>{account ? `${member?.role ?? "member"}: ${account.displayName} (${account.email})` : "Not yet assigned to a hotel partner."}</p></div></article>)}</div></section></div>;
}
