"use client";
import { useEffect, useState } from "react";

type Customer = { displayName: string; email: string; phone: string | null; profileImageUrl: string | null };
type CustomPackage = { id: string; name: string; travelStartDate: string; travelEndDate: string; adults: number; children: number; status: string; destinationSlug: string };

export function AccountHome() { const [customer, setCustomer] = useState<Customer | null>(null); useEffect(() => { fetch("/api/account/profile").then(response => response.json()).then(data => setCustomer(data.customer ?? null)).catch(() => setCustomer(null)); }, []); return <main className="account-page"><section className="container account-hero"><p className="eyebrow">My account</p><h1>{customer ? `Welcome, ${customer.displayName}.` : "Your JournAway account."}</h1><p>Keep your custom trip preferences in one private place.</p><div className="button-row"><a className="button button-primary" href="/custom-package">Build a custom trip</a><a className="button button-secondary" href="/account/custom-packages">My custom trips</a></div></section></main>; }
export function CustomPackageList() { const [packages, setPackages] = useState<CustomPackage[]>([]); const [message, setMessage] = useState("Loading your custom trips…"); useEffect(() => { fetch("/api/custom-packages").then(async response => { const data = await response.json() as { packages?: CustomPackage[]; error?: string }; if (!response.ok) throw new Error(data.error); return data; }).then(data => { setPackages(data.packages ?? []); setMessage(""); }).catch(error => setMessage(error instanceof Error ? error.message : "Unable to load your custom trips.")); }, []); return <main className="account-page"><section className="container"><p className="eyebrow">My custom trips</p><h1>Trip requests, privately yours.</h1>{message && <p className="operations-notice">{message}</p>}{packages.length ? <div className="customer-trip-list">{packages.map(item => <article key={item.id}><span>{item.status.replace("_", " ")}</span><h2>{item.name}</h2><p>{item.travelStartDate} to {item.travelEndDate} · {item.adults} adults, {item.children} children</p></article>)}</div> : !message && <div className="operations-notice">You have not submitted a custom trip yet. <a href="/custom-package">Build one now.</a></div>}</section></main>; }
export function CustomerProfile() { const [customer, setCustomer] = useState<Customer | null>(null); const [phone, setPhone] = useState(""); const [message, setMessage] = useState("Loading profile…"); useEffect(() => { fetch("/api/account/profile").then(response => response.json()).then(data => { setCustomer(data.customer ?? null); setPhone(data.customer?.phone ?? ""); setMessage(""); }).catch(() => setMessage("Unable to load profile.")); }, []); const save = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const response = await fetch("/api/account/profile", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ phone }) }); const data = await response.json() as { error?: string; customer?: Customer }; if (!response.ok) setMessage(data.error ?? "Unable to save profile."); else { setCustomer(data.customer ?? null); setMessage("Profile saved."); } }; return <main className="account-page"><section className="container account-profile"><p className="eyebrow">Profile</p><h1>Your travel contact details.</h1>{customer && <form className="operations-form" onSubmit={save}><label>Name<input value={customer.displayName} readOnly /></label><label>Email<input value={customer.email} readOnly /></label><label>Phone<input value={phone} onChange={event => setPhone(event.target.value)} /></label><button className="button button-primary" type="submit">Save phone</button></form>}{message && <p className="operations-notice">{message}</p>}</section></main>; }
