"use client";

import { useEffect, useRef, useState, type FormEvent, type ReactNode } from "react";

type TravelMode = "tours" | "cabs" | "hotels";
type Customer = { displayName: string; email: string };

export function EnquiryAccountGate({ returnTo, children }: { returnTo: string; children: (customer: Customer) => ReactNode }) {
  const [customer, setCustomer] = useState<Customer | null | undefined>(undefined);
  useEffect(() => { fetch("/api/auth/session").then(response => response.json()).then(data => setCustomer(data.customer ?? null)).catch(() => setCustomer(null)); }, []);
  if (customer === undefined) return <p className="operations-notice">Checking your account…</p>;
  if (!customer) return <div className="enquiry-auth-gate"><p className="eyebrow">Account required</p><h3>Sign in to send an enquiry.</h3><p>Create a JournAway account or log in so we can keep your travel requests and updates in one place.</p><div className="button-row"><a className="button button-primary" href={`/login?return_to=${encodeURIComponent(returnTo)}`}>Log in</a><a className="button button-secondary" href={`/signup?return_to=${encodeURIComponent(returnTo)}`}>Create account</a></div></div>;
  return <>{children(customer)}</>;
}

export function JourneySearch() {
  const [mode, setMode] = useState<TravelMode>("tours");
  const [travellers, setTravellers] = useState(1);
  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    if (mode === "cabs") {
      const params = new URLSearchParams();
      ["pickup", "drop", "date"].forEach(key => { const value = String(data.get(key) ?? ""); if (value) params.set(key, value); });
      window.location.assign(`/vehicle-rental?${params.toString()}`);
      return;
    }
    window.location.assign(mode === "tours" ? "/tours" : "/hotels");
  }
  return <form className="journey-search glass-panel glass-strong" onSubmit={submit}>
    <div className="search-heading"><div><p className="eyebrow">Start your journey</p><h2>{mode === "tours" ? "Find a remarkable route." : mode === "cabs" ? "Find the right ride." : "Find the right stay."}</h2></div><p>{mode === "tours" ? "Explore curated journeys through Ladakh and Kashmir." : mode === "cabs" ? "Continue to our vehicle rental service to plan your road journey." : "Share your stay details and request a hotel booking with JournAway."}</p></div>
    <div className="search-tabs" role="tablist" aria-label="Travel service"><button type="button" role="tab" aria-selected={mode === "tours"} className={mode === "tours" ? "active" : ""} onClick={() => setMode("tours")}>Tours</button><button type="button" role="tab" aria-selected={mode === "cabs"} className={mode === "cabs" ? "active" : ""} onClick={() => setMode("cabs")}>Cabs</button><button type="button" role="tab" aria-selected={mode === "hotels"} className={mode === "hotels" ? "active" : ""} onClick={() => setMode("hotels")}>Hotels</button></div>
    {mode === "tours" ? <div className="search-fields" role="tabpanel"><label>Destination<input required name="destination" placeholder="Ladakh, Kashmir, or a place in mind" /></label><label>Travel date<input name="date" type="date" /></label><div className="traveller-field" role="group" aria-label="Travellers"><span>Travellers</span><div className="stepper"><button type="button" onClick={() => setTravellers(Math.max(1, travellers - 1))} aria-label="Remove traveller">-</button><span>{travellers} traveller{travellers > 1 ? "s" : ""}</span><button type="button" onClick={() => setTravellers(travellers + 1)} aria-label="Add traveller">+</button></div></div><button className="button button-primary search-submit" type="submit">Find tours <span aria-hidden="true">→</span></button></div> : mode === "cabs" ? <div className="search-fields cab-search-fields" role="tabpanel"><label>Pickup<input required name="pickup" placeholder="Starting point" /></label><label>Drop<input required name="drop" placeholder="Destination" /></label><label>Travel date<input name="date" type="date" /></label><button className="button button-primary search-submit" type="submit">Book a cab <span aria-hidden="true">→</span></button></div> : <div className="search-fields hotel-search-fields" role="tabpanel"><label>Destination<input required name="destination" placeholder="Where are you staying?" /></label><label>Check-in<input required name="check-in" type="date" /></label><label>Check-out<input required name="check-out" type="date" /></label><button className="button button-primary search-submit" type="submit">Find hotels <span aria-hidden="true">→</span></button></div>}
  </form>;
}

export function CabSearch() {
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const params = new URLSearchParams(); ["pickup", "drop", "date"].forEach(key => { const value = String(data.get(key) ?? ""); if (value) params.set(key, value); }); window.location.assign(`/vehicle-rental?${params.toString()}`); }
  return <form className="cab-search glass-panel glass-strong" onSubmit={submit}><p className="eyebrow">Vehicle rental</p><h2>Set the road in motion.</h2><p>Plan local transportation, airport transfers, outstation travel, or group movement with JournAway.</p><div className="cab-search-fields"><label>Pickup<input required name="pickup" placeholder="Starting point" /></label><label>Drop<input required name="drop" placeholder="Destination" /></label><label>Date<input name="date" type="date" /></label></div><button className="button button-primary" type="submit">Explore cabs <span aria-hidden="true">→</span></button></form>;
}

export function HotelRequestForm() {
  const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const formStartedAt = useRef(Date.now());
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const form = event.currentTarget; const data = new FormData(form); try { const response = await fetch("/api/enquiries", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ type: "hotel", name: data.get("name"), email: data.get("email"), phone: data.get("phone"), destination: data.get("destination"), guests: Number(data.get("guests")), travelStartDate: data.get("checkIn"), travelEndDate: data.get("checkOut"), message: data.get("message"), website: data.get("website"), formStartedAt: formStartedAt.current }) }); const body = await response.json() as { error?: string }; if (!response.ok) throw new Error(body.error ?? "Unable to send your hotel request."); form.reset(); setMessage("Your hotel request is with the JournAway team. We’ll contact you with suitable options."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to send your hotel request."); } finally { setBusy(false); } }
  return <EnquiryAccountGate returnTo="/hotels">{customer => <form className="hotel-request" onSubmit={submit}><input className="form-honeypot" name="website" tabIndex={-1} autoComplete="off" aria-hidden="true" /><div className="form-grid"><label>Your name<input required name="name" autoComplete="name" defaultValue={customer.displayName} readOnly /></label><label>Phone number<input required name="phone" type="tel" autoComplete="tel" placeholder="Phone number" /></label><label>Email address<input required name="email" type="email" autoComplete="email" defaultValue={customer.email} readOnly /></label><label>Destination<input required name="destination" placeholder="Ladakh, Kashmir, or a place in mind" /></label><label>Guests<input required name="guests" type="number" min="1" max="30" placeholder="Number of guests" /></label><label>Check-in<input required name="checkIn" type="date" /></label><label>Check-out<input required name="checkOut" type="date" /></label><label className="form-full">Stay preferences<textarea name="message" placeholder="Room type, budget, or anything else that matters" rows={4} /></label></div><button className="button button-primary" type="submit" disabled={busy}>{busy ? "Sending…" : <>Request hotel options <span aria-hidden="true">→</span></>}</button>{message && <p className="form-notice" role="status">{message}</p>}</form>}</EnquiryAccountGate>;
}

export function EnquiryForm() {
  const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const formStartedAt = useRef(Date.now());
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const form = event.currentTarget; const data = new FormData(form); try { const response = await fetch("/api/enquiries", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ type: "contact", name: data.get("name"), phone: data.get("phone"), email: data.get("email"), service: data.get("service"), message: data.get("message"), website: data.get("website"), formStartedAt: formStartedAt.current }) }); const body = await response.json() as { error?: string }; if (!response.ok) throw new Error(body.error ?? "Unable to submit your enquiry."); form.reset(); setMessage("Thank you. Your enquiry has been sent to the JournAway team."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to submit your enquiry."); } finally { setBusy(false); } }
  return <EnquiryAccountGate returnTo="/contact">{customer => <form className="enquiry-form" onSubmit={submit}><input className="form-honeypot" name="website" tabIndex={-1} autoComplete="off" aria-hidden="true" /><div className="form-grid"><label>Your name<input required name="name" autoComplete="name" defaultValue={customer.displayName} readOnly /></label><label>Phone number<input required name="phone" type="tel" autoComplete="tel" inputMode="tel" placeholder="Phone Number *" /></label><label>Email address<input required name="email" type="email" autoComplete="email" defaultValue={customer.email} readOnly /></label><label>Trip interest<select required name="service" defaultValue=""><option value="" disabled>Select a service</option><option>Tour package</option><option>Vehicle rental</option><option>Hotel booking</option><option>Custom trip planning</option></select></label><label className="form-full">Tell us about your journey<textarea required name="message" placeholder="Write your message *" rows={5} /></label></div><button className="button button-primary" type="submit" disabled={busy}>{busy ? "Sending…" : <>Submit enquiry <span aria-hidden="true">→</span></>}</button>{message && <p className="form-notice" role="status">{message}</p>}</form>}</EnquiryAccountGate>;
}
