"use client";

import { useEffect, useMemo, useState } from "react";
import { showcaseTours } from "./site-data";
import { Button, TourCard } from "./ui";

type DiscoveryKind = "tours" | "packages";
type SortOrder = "recommended" | "shortest" | "longest";
type PublishedPackage = { slug: string; name: string; destination: string; duration: string; description: string; image: string; priceInr: number };
const heroImage = "https://upload.wikimedia.org/wikipedia/commons/f/fd/Pangong_Lake%2C_Ladakh%2C_India_02.jpg";
const destinations = ["All journeys", "Ladakh", "Pangong Lake", "Kashmir"];
const durationDays = (duration: string) => Number.parseInt(duration, 10) || 0;

export function TourDiscovery({ kind }: { kind: DiscoveryKind }) {
  const [query, setQuery] = useState(""); const [destination, setDestination] = useState("All journeys"); const [sort, setSort] = useState<SortOrder>("recommended"); const [publishedPackages, setPublishedPackages] = useState<PublishedPackage[]>([]); const [packagesReady, setPackagesReady] = useState(kind !== "packages");
  useEffect(() => { if (kind !== "packages") return; fetch("/api/packages").then(async response => { if (!response.ok) throw new Error("Unable to load packages."); return response.json() as Promise<{ packages: PublishedPackage[] }>; }).then(data => setPublishedPackages(data.packages)).catch(() => setPublishedPackages([])).finally(() => setPackagesReady(true)); }, [kind]);
  const title = kind === "tours" ? "Find a journey worth taking." : "Packages made for the open road.";
  const label = kind === "tours" ? "Tours" : "Tour packages";
  const results = useMemo(() => { const normalizedQuery = query.trim().toLowerCase(); const source = kind === "packages" ? publishedPackages : showcaseTours; return source.filter(tour => (destination === "All journeys" || tour.destination.includes(destination)) && (!normalizedQuery || `${tour.name} ${tour.destination} ${tour.duration}`.toLowerCase().includes(normalizedQuery))).sort((a, b) => sort === "shortest" ? durationDays(a.duration) - durationDays(b.duration) : sort === "longest" ? durationDays(b.duration) - durationDays(a.duration) : 0); }, [destination, kind, publishedPackages, query, sort]);
  const clear = () => { setQuery(""); setDestination("All journeys"); setSort("recommended"); };

  return <main className="tour-discovery-page"><section className="discovery-hero" style={{ backgroundImage: `linear-gradient(90deg, rgba(7,31,22,.78), rgba(12,52,36,.34)), url('${heroImage}')` }}><div className="container"><div className="discovery-hero-content glass-dark"><p className="eyebrow light">Explore JournAway</p><h1>{title}</h1><p>Browse the published Ladakh and Kashmir journeys, then send an enquiry when one feels right for you.</p></div></div></section><section className="discovery-content"><div className="container"><div className="tour-filter-panel glass-panel glass-strong"><label className="tour-search-label">Search journeys<input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search destination or tour" /></label><div className="quick-destinations" aria-label="Filter by destination">{destinations.map(item => <button key={item} className={destination === item ? "active" : ""} type="button" onClick={() => setDestination(item)} aria-pressed={destination === item}>{item}</button>)}</div><label className="sort-control">Sort journeys<select value={sort} onChange={event => setSort(event.target.value as SortOrder)}><option value="recommended">Recommended</option><option value="shortest">Shortest duration</option><option value="longest">Longest duration</option></select></label></div><div className="discovery-results-header"><div><p className="eyebrow">Published {kind}</p><h2>{label}</h2><p aria-live="polite">{packagesReady ? `${results.length} ${results.length === 1 ? "journey" : "journeys"} shown` : "Loading packages…"}</p></div>{(query || destination !== "All journeys" || sort !== "recommended") && <button type="button" className="clear-filters" onClick={clear}>Clear filters</button>}</div>{!packagesReady ? <p className="operations-notice">Loading published packages…</p> : results.length ? <div className="tour-grid discovery-tour-grid">{results.map(tour => <TourCard key={tour.slug} tour={tour} detailBase={kind === "tours" ? "/tours" : "/tour-packages"} />)}</div> : <div className="tour-empty"><p className="eyebrow">No matching journeys</p><h2>Try a different destination.</h2><p>Adjust the search or destination filter to see the published trips again.</p><button type="button" className="button button-secondary" onClick={clear}>Clear filters <span aria-hidden="true">→</span></button></div>}<section className="tour-discovery-cta"><div><p className="eyebrow light">A journey, your way</p><h2>Can’t find the right trip?</h2><p>Tell us what you have in mind and the JournAway team can help plan the route, stay, and travel details.</p></div><div className="button-row"><Button href="/contact">Plan your trip</Button><Button href="/vehicle-rental" variant="secondary">Explore cabs</Button></div></section></div></section></main>;
}
