"use client";
import "./trip-document.css";
import { useEffect, useState } from "react";
import { confirmationErrors, dateAt, type TripDocumentDetails, type TripSummary } from "@/lib/trip-document";

type State = { trip: TripSummary & { status: string }; customer: { displayName: string; email: string }; document: { details: TripDocumentDetails; revision: number; confirmedAt: string | null }; delivery: string };
type TextKey = Exclude<keyof TripDocumentDetails, "hotels" | "days" | "totalInr" | "coverPhoto">;
const labels: Array<[TextKey, string]> = [["taxNote", "Tax note (included / excluded)"], ["vehicle", "Vehicle and transport arrangement"], ["specialInclusions", "Other special inclusions"], ["inclusions", "Inclusions"], ["exclusions", "Exclusions"], ["terms", "Terms and conditions"], ["paymentTerms", "Payment terms"], ["paymentDetails", "JournAway payment / bank details (optional)"], ["cancellationPolicy", "Cancellation policy"], ["consultant", "Consultant name"], ["phone", "Contact phone"], ["email", "Contact email"], ["address", "Office address"], ["website", "Website"]];

function PhotoField({ value, onChange }: { value: string; onChange: (photo: string) => void }) {
  const [error, setError] = useState(""); const [processing, setProcessing] = useState(false);
  async function upload(file?: File) {
    if (!file) return; setError(""); setProcessing(true);
    let bitmap: ImageBitmap | undefined;
    try {
      if (!/^image\/(jpeg|png)$/.test(file.type) || file.size > 8_000_000) throw new Error("Choose a JPG or PNG under 8 MB.");
      bitmap = await createImageBitmap(file); const scale = Math.min(1, 1200 / Math.max(bitmap.width, bitmap.height));
      const canvas = document.createElement("canvas"); canvas.width = Math.round(bitmap.width * scale); canvas.height = Math.round(bitmap.height * scale);
      const context = canvas.getContext("2d"); if (!context) throw new Error("Photo processing unavailable.");
      context.fillStyle = "white"; context.fillRect(0, 0, canvas.width, canvas.height); context.drawImage(bitmap, 0, 0, canvas.width, canvas.height);
      const photo = canvas.toDataURL("image/jpeg", .72); if (photo.length > 400_000) throw new Error("Use a smaller photo (under 300 KB after compression)."); onChange(photo);
    } catch (e) { setError(e instanceof Error ? e.message : "Unable to use photo."); }
    finally { bitmap?.close(); setProcessing(false); }
  }
  return <div className="trip-photo-field"><label>Photo<select value={value.startsWith("data:") ? "upload" : value} onChange={e => { if (e.target.value !== "upload") onChange(e.target.value); }}><option value="">No photo</option><option value="pangong">Pangong Lake, Ladakh</option>{value.startsWith("data:") && <option value="upload">Uploaded photo</option>}</select></label><label>Upload Ladakh / Kashmir or hotel photo<input type="file" accept="image/jpeg,image/png" disabled={processing} onChange={e => void upload(e.target.files?.[0])} /></label>{value.startsWith("data:") && <img src={value} alt="Uploaded itinerary" width="140" />}{processing && <p>Preparing photo…</p>}{error && <p role="alert">{error}</p>}</div>;
}

export function TripDocumentEditor({ tripId }: { tripId: string }) {
  const endpoint = `/api/admin/custom-packages/${tripId}/document`;
  const [state, setState] = useState<State | null>(null); const [details, setDetails] = useState<TripDocumentDetails | null>(null);
  const [message, setMessage] = useState("Loading itinerary…"); const [busy, setBusy] = useState(false); const [dirty, setDirty] = useState(false);
  const [preview, setPreview] = useState<string | null>(null); const [previewRevision, setPreviewRevision] = useState<number | null>(null); const [approved, setApproved] = useState(false);
  useEffect(() => { let active = true; fetch(endpoint).then(async r => { const data = await r.json(); if (!r.ok) throw new Error(data.error); return data; }).then(data => { if (active) { setState(data); setDetails(data.document.details); setDirty(false); setMessage(""); } }).catch(e => { if (active) setMessage(e instanceof Error ? e.message : "Unable to load trip."); }); return () => { active = false; }; }, [endpoint]);
  useEffect(() => () => { if (preview) URL.revokeObjectURL(preview); }, [preview]);
  function change<K extends keyof TripDocumentDetails>(key: K, value: TripDocumentDetails[K]) { setDetails(current => current ? { ...current, [key]: value } : current); setDirty(true); setApproved(false); setPreviewRevision(null); }
  async function save() {
    if (!state || !details) return; setBusy(true); setMessage("");
    try { const r = await fetch(endpoint, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ revision: state.document.revision, details }) }); const data = await r.json(); if (!r.ok) throw new Error(data.error); setState({ ...state, document: data.document }); setDetails(data.document.details); setDirty(false); setPreviewRevision(null); setApproved(false); setMessage("Itinerary saved. Preview the PDF before confirming."); }
    catch (e) { setMessage(e instanceof Error ? e.message : "Unable to save."); } finally { setBusy(false); }
  }
  async function showPreview() {
    if (!state) return; setBusy(true); setMessage("");
    try { const r = await fetch(`${endpoint}?pdf=1`); if (!r.ok) throw new Error("PDF preview failed. Check the photos and try again."); const blob = await r.blob(); if (blob.type !== "application/pdf") throw new Error("The server did not return a PDF."); setPreview(URL.createObjectURL(blob)); setPreviewRevision(state.document.revision); }
    catch (e) { setMessage(e instanceof Error ? e.message : "Unable to preview."); } finally { setBusy(false); }
  }
  async function send(action: "confirm" | "retry") {
    if (!state) return; setBusy(true); setMessage("");
    try { const r = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, revision: state.document.revision }) }); const data = await r.json(); if (!r.ok) throw new Error(data.error); setState({ ...state, trip: { ...state.trip, status: "confirmed" }, document: data.document, delivery: data.delivery }); setPreview(null); setMessage(data.delivery === "sent" ? "Trip confirmed. The SMTP server accepted the PDF email." : data.delivery === "failed" ? "Trip confirmed and PDF saved, but email failed. Check SMTP settings, then retry below." : "Trip confirmed. Email delivery is pending or uncertain; check the mailbox provider logs before attempting any manual resend."); }
    catch (e) { setMessage(e instanceof Error ? e.message : "Unable to confirm."); } finally { setBusy(false); }
  }
  if (!state || !details) return <section className="admin-panel"><p role="status">{message}</p><a href="/admin/custom-packages">Back to trip requests</a></section>;
  const locked = Boolean(state.document.confirmedAt); const errors = confirmationErrors(details, state.trip);
  return <div className="trip-document-editor"><a href="/admin/custom-packages">← Trip requests</a><section className="admin-panel"><p className="eyebrow">{state.trip.sourcePackageSlug ? "Selected package" : "Custom trip"}</p><h2>{state.trip.name}</h2><p>{state.customer.displayName} · {state.customer.email}</p><p>{state.trip.travelStartDate} to {state.trip.travelEndDate} · {state.trip.adults} adults, {state.trip.children} children</p><p>Status: {state.trip.status} · PDF email: {state.delivery.replace("_", " ")}</p>{locked && <p>The approved itinerary is saved and locked. Downloading or retrying uses the same PDF.</p>}</section>
    <fieldset disabled={locked || busy} className="trip-editor-fields"><legend>Itinerary details</legend><section className="admin-panel"><h3>Cover and price</h3><label>Final total (INR)<input type="number" min="1" max="100000000" step="1" value={details.totalInr || ""} onChange={e => change("totalInr", Number(e.target.value))} /></label><PhotoField value={details.coverPhoto} onChange={value => change("coverPhoto", value)} /></section>
    <section className="admin-panel"><h3>Hotels / Accommodations</h3><p>Leave empty only when accommodation is not included.</p>{details.hotels.map((hotel, i) => <div className="trip-editor-card" key={i}><h4>Stay {i + 1}</h4><div className="trip-document-grid">{([['name', 'Hotel name'], ['location', 'City / location'], ['checkIn', 'Check-in date'], ['category', 'Category / stars'], ['rooms', 'Rooms and occupancy'], ['meals', 'Meal plan']] as const).map(([key, label]) => <label key={key}>{label}<input type={key === "checkIn" ? "date" : "text"} value={hotel[key]} onChange={e => change("hotels", details.hotels.map((h, n) => n === i ? { ...h, [key]: e.target.value } : h))} /></label>)}<label>Nights<input type="number" min="1" max="30" value={hotel.nights} onChange={e => change("hotels", details.hotels.map((h, n) => n === i ? { ...h, nights: Number(e.target.value) } : h))} /></label></div><PhotoField value={hotel.photo} onChange={photo => change("hotels", details.hotels.map((h, n) => n === i ? { ...h, photo } : h))} /><button type="button" onClick={() => change("hotels", details.hotels.filter((_, n) => n !== i))}>Remove stay</button></div>)}<button type="button" disabled={details.hotels.length >= 31} onClick={() => change("hotels", [...details.hotels, { name: "", location: "", checkIn: state.trip.travelStartDate, nights: 1, category: "", rooms: "", meals: "", photo: "" }])}>Add hotel stay</button></section>
    <section className="admin-panel"><h3>Day Wise Itinerary</h3>{details.days.map((day, i) => <div className="trip-editor-card" key={i}><h4>Day {i + 1} · {dateAt(state.trip.travelStartDate, i)}</h4>{([['title', 'Day title'], ['transport', 'Transport / route'], ['description', 'Activities and itinerary']] as const).map(([key, label]) => <label key={key}>{label}<textarea rows={key === "description" ? 5 : 2} value={day[key]} onChange={e => change("days", details.days.map((d, n) => n === i ? { ...d, [key]: e.target.value } : d))} /></label>)}<PhotoField value={day.photo} onChange={photo => change("days", details.days.map((d, n) => n === i ? { ...d, photo } : d))} /></div>)}</section>
    <section className="admin-panel"><h3>Inclusions, terms and contact</h3><p>Enter JournAway’s approved policies and payment details. These appear in the customer’s PDF.</p><div className="trip-document-grid">{labels.map(([key, label]) => <label key={key}>{label}<textarea rows={["terms", "paymentTerms", "cancellationPolicy", "paymentDetails", "inclusions", "exclusions"].includes(key) ? 6 : 2} value={details[key]} onChange={e => change(key, e.target.value)} /></label>)}</div></section></fieldset>
    <section className="admin-panel trip-document-actions">{message && <p role="status">{message}</p>}{!locked && errors.length > 0 && <details><summary>{errors.length} items to complete before confirmation</summary><ul>{errors.map(error => <li key={error}>{error}</li>)}</ul></details>}<div className="button-row">{!locked && <button className="button button-secondary" disabled={busy || !dirty} onClick={save}>Save itinerary</button>}<button className="button button-secondary" disabled={busy || dirty} onClick={showPreview}>{locked ? "View approved PDF" : "Preview saved PDF"}</button>{locked && state.trip.status !== "cancelled" && ["failed", "not_sent"].includes(state.delivery) && <button className="button button-primary" disabled={busy} onClick={() => send("retry")}>Retry PDF email</button>}</div>{!locked && <><label className="trip-approval"><input type="checkbox" checked={approved} disabled={dirty || previewRevision !== state.document.revision} onChange={e => setApproved(e.target.checked)} /> I reviewed the saved PDF, final price, hotel details and policies.</label><button className="button button-primary" disabled={busy || dirty || !approved || errors.length > 0 || state.trip.status === "cancelled"} onClick={() => send("confirm")}>{busy ? "Working…" : "Confirm trip & email PDF"}</button></>}{preview && <><p><a href={preview} target="_blank" rel="noreferrer">Open PDF in a new tab</a></p><iframe className="trip-pdf-preview" title="Trip itinerary PDF preview" src={preview} /></>}</section></div>;
}
