import type { HTMLAttributes, ReactNode } from "react";
import { formatInr } from "@/lib/package-images";

type ButtonProps = { href?: string; children: ReactNode; variant?: "primary" | "secondary" | "ghost"; className?: string };
export function Button({ href, children, variant = "primary", className = "" }: ButtonProps) { const classNames = `button button-${variant} ${className}`; return href ? <a className={classNames} href={href}>{children}<span aria-hidden="true">→</span></a> : <button className={classNames} type="submit">{children}<span aria-hidden="true">→</span></button>; }
export function Chip({ children }: { children: ReactNode }) { return <span className="chip">{children}</span>; }
export function GlassPanel({ children, className = "", variant = "light", ...props }: HTMLAttributes<HTMLDivElement> & { children: ReactNode; variant?: "light" | "strong" | "dark" }) { return <div className={`glass-panel glass-${variant} ${className}`} {...props}>{children}</div>; }
type Tour = { slug: string; destination: string; name: string; duration: string; image: string; priceInr?: number };
export function TourCard({ tour, detailBase = "/tours" }: { tour: Tour; detailBase?: "/tours" | "/tour-packages" }) { return <article className="tour-card"><div className="tour-card-image"><img src={tour.image} alt={`${tour.name} in ${tour.destination}`} loading="lazy" /></div><div className="tour-card-content"><p className="location-label">{tour.destination}</p><h3>{tour.name}</h3><div className="tour-card-meta"><Chip>{tour.duration}</Chip>{typeof tour.priceInr === "number" && <strong className="tour-card-price">{formatInr(tour.priceInr)}</strong>}</div><a className="card-link" href={`${detailBase}/${tour.slug}`}>View journey <span aria-hidden="true">→</span></a></div></article>; }
type Destination = { slug: string; name: string; subtitle: string; image: string };
export function DestinationCard({ destination }: { destination: Destination }) { return <a className="destination-card" href={`/destinations/${destination.slug}`}><img src={destination.image} alt={`${destination.name} landscape`} loading="lazy" /><div><p>{destination.subtitle}</p><h3>{destination.name}</h3><span>Explore <b aria-hidden="true">→</b></span></div></a>; }
export function EmptyResults({ type }: { type: "tours" | "packages" | "vehicles" }) { const label = type === "vehicles" ? "vehicles" : type; return <div className="empty-results"><span aria-hidden="true">⌁</span><h2>No {label} available right now</h2><p>We could not find published {label} matching those filters. Our team can still help plan the right journey.</p><Button href="/contact" variant="secondary">Get a trip quote</Button></div>; }
