import nodemailer from "nodemailer";
import { and, eq } from "drizzle-orm";
import { emailNotifications } from "../../backend/db/schema";
import { getOperationsDb } from "@/lib/operations-api";
import { tripEmailKey } from "./trip-document-service";

type CustomTrip = { id: string; customerId: string; name: string; destination: string; travelStartDate: string; travelEndDate: string };
export type EnquiryEmailInput = { id: string; type: "contact" | "cab" | "hotel"; service: string | null; name: string; email: string; phone: string; destination: string | null; pickupLocation: string | null; dropoffLocation: string | null; travelStartDate: string | null; travelEndDate: string | null; guests: number | null; message: string | null; status?: "new" | "in_progress" | "closed" };
type AccessAccount = { id: string; role: "driver" | "hotel"; email: string; displayName: string; status: "pending" | "active" | "suspended"; createdAt: string };

const escapeHtml = (value: string) => value.replace(/[&<>'"]/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[char] ?? char);
const siteUrl = () => (process.env.PUBLIC_SITE_URL ?? "").replace(/\/$/, "");
const mailFrom = () => { const name = process.env.MAIL_FROM_NAME?.trim() || "JournAway"; const address = process.env.MAIL_FROM_ADDRESS?.trim(); return address ? `${name} <${address}>` : null; };
const adminRecipients = () => [...new Set((process.env.ADMIN_NOTIFICATION_EMAIL ?? process.env.JOURNAWAY_ENQUIRY_EMAILS ?? "").split(",").map(value => value.trim().toLowerCase()).filter(value => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)))];

let transporter: nodemailer.Transporter | undefined;
/** Explicit retries claim only failed rows; sent or in-flight mail is never sent again. */
export async function sendTripDocumentEmail(input: { tripId: string; customerId: string; recipient: string; tripName: string; pdf: Buffer; retry: boolean }): Promise<string> {
  const db = getOperationsDb(); const eventKey = tripEmailKey(input.tripId);
  const subject = `Your JournAway trip is confirmed: ${input.tripName}`;
  let [notice] = await db.insert(emailNotifications).values({ id: crypto.randomUUID(), eventKey, customerId: input.customerId, recipientEmail: input.recipient, subject }).onConflictDoNothing().returning();
  if (!notice && input.retry) [notice] = await db.update(emailNotifications).set({ status: "pending" }).where(and(eq(emailNotifications.eventKey, eventKey), eq(emailNotifications.status, "failed"))).returning();
  if (!notice) { const [existing] = await db.select({ status: emailNotifications.status }).from(emailNotifications).where(eq(emailNotifications.eventKey, eventKey)); return existing?.status ?? "not_sent"; }
  let sent;
  try {
    const from = mailFrom(); if (!from) throw new Error("MAIL_FROM_ADDRESS is required.");
    sent = await smtp().sendMail({ from, to: input.recipient, subject,
      html: shell("Your journey is confirmed", `<p>Your approved itinerary for <strong>${escapeHtml(input.tripName)}</strong> is attached as a PDF.</p><p>You can also download it from your JournAway account.</p>`),
      text: `Your JournAway trip ${input.tripName} is confirmed. Your personalised itinerary PDF is attached.`,
      attachments: [{ filename: `JournAway-trip-${input.tripId}.pdf`, content: input.pdf, contentType: "application/pdf" }],
    });
  } catch (error) {
    const err = error as { code?: string; command?: string; responseCode?: number };
    const ambiguous = ["ETIMEDOUT", "ESOCKET", "ECONNECTION"].includes(err.code ?? "") && /DATA/i.test(err.command ?? "");
    const status = ambiguous ? "pending" : "failed";
    console.error("Trip PDF email failed", { eventKey, code: err.code, command: err.command, responseCode: err.responseCode });
    await db.update(emailNotifications).set({ status }).where(eq(emailNotifications.id, notice.id)); return status;
  }
  // SMTP has accepted this email. A ledger failure must not allow duplicate delivery.
  try { await db.update(emailNotifications).set({ status: "sent", providerMessageId: sent.messageId, sentAt: new Date().toISOString() }).where(eq(emailNotifications.id, notice.id)); }
  catch { console.error("Trip email accepted; delivery ledger update failed", { eventKey }); return "pending"; }
  return "sent";
}
function smtp() { if (transporter) return transporter; const host = process.env.SMTP_HOST?.trim(); const user = process.env.SMTP_USER?.trim(); const pass = process.env.SMTP_PASSWORD; if (!host || !user || !pass) throw new Error("SMTP email configuration is incomplete."); transporter = nodemailer.createTransport({ host, port: Number(process.env.SMTP_PORT ?? 587), secure: process.env.SMTP_SECURE === "true", auth: { user, pass }, connectionTimeout: 10_000, socketTimeout: 15_000 }); return transporter; }
function shell(title: string, body: string) { return `<main style="max-width:600px;margin:0 auto;padding:28px 18px;background:#f6f4ec;font-family:Arial,sans-serif;color:#19221d"><section style="padding:26px;background:#163a2b;color:#fff;border-radius:14px 14px 0 0"><strong style="letter-spacing:1px">JOURNAWAY</strong><h1 style="margin:16px 0 0;font-size:26px">${escapeHtml(title)}</h1></section><section style="padding:26px;background:#fff;border-radius:0 0 14px 14px">${body}</section></main>`; }
function rows(values: Array<[string, string | null | undefined]>) { return `<table style="width:100%;border-collapse:collapse">${values.filter(([, value]) => Boolean(value)).map(([label, value]) => `<tr><td style="padding:9px 0;border-bottom:1px solid #e5e9e2">${escapeHtml(label)}</td><td style="padding:9px 0;border-bottom:1px solid #e5e9e2;text-align:right"><strong>${escapeHtml(value!)}</strong></td></tr>`).join("")}</table>`; }
async function send({ eventKey, recipient, subject, html, text, customerId, replyTo }: { eventKey: string; recipient: string; subject: string; html: string; text: string; customerId?: string; replyTo?: string }) { const db = getOperationsDb(); const [notice] = await db.insert(emailNotifications).values({ id: crypto.randomUUID(), eventKey, customerId: customerId ?? null, recipientEmail: recipient, subject }).onConflictDoNothing().returning(); if (!notice) return; try { const from = mailFrom(); if (!from) throw new Error("MAIL_FROM_ADDRESS is required."); const sent = await smtp().sendMail({ from, to: recipient, replyTo, subject, html, text }); await db.update(emailNotifications).set({ status: "sent", providerMessageId: sent.messageId, sentAt: new Date().toISOString() }).where(eq(emailNotifications.id, notice.id)); } catch (error) { console.error("SMTP notification failed", { eventKey, error }); await db.update(emailNotifications).set({ status: "failed" }).where(eq(emailNotifications.id, notice.id)); } }
async function sendAdmins(eventKey: string, subject: string, html: string, text: string, replyTo?: string) { await Promise.all(adminRecipients().map(recipient => send({ eventKey: `${eventKey}:${recipient}`, recipient, subject, html, text, replyTo }))); }

export async function sendCustomPackageReceivedEmail(input: CustomTrip, recipient: string) { const subject = "JournAway received your custom trip request"; await send({ eventKey: `custom-trip:${input.id}:submitted:customer:${recipient}`, recipient, customerId: input.customerId, subject, html: shell("Your custom trip request is received.", `<p>Hi,</p><p>Our travel team will review <strong>${escapeHtml(input.name)}</strong> and contact you with next steps.</p>${rows([["Destination", input.destination], ["Travel dates", `${input.travelStartDate} to ${input.travelEndDate}`], ["Status", "Submitted for review"]])}`), text: `We received ${input.name}. Destination: ${input.destination}. Travel dates: ${input.travelStartDate} to ${input.travelEndDate}.` }); }
export async function sendCustomPackageAdminNotification(input: CustomTrip, customerEmail: string) { const subject = `New JournAway custom trip enquiry: ${input.name}`; await sendAdmins(`custom-trip:${input.id}:submitted:admin`, subject, shell("New custom trip enquiry", `<p>A customer has submitted a custom trip request.</p>${rows([["Customer", customerEmail], ["Trip", input.name], ["Destination", input.destination], ["Travel dates", `${input.travelStartDate} to ${input.travelEndDate}`]])}<p><a href="${siteUrl()}/admin/custom-packages">Review custom trip</a></p>`), `New custom trip enquiry from ${customerEmail}: ${input.name}.` , customerEmail); }
export async function sendCustomPackageConfirmedEmail(input: CustomTrip, recipient: string) { const subject = "Your JournAway custom trip is confirmed"; await send({ eventKey: `custom-trip:${input.id}:confirmed:customer:${recipient}`, recipient, customerId: input.customerId, subject, html: shell("Your custom trip is confirmed.", `<p>Hi,</p><p>Your request for <strong>${escapeHtml(input.name)}</strong> is confirmed. Our team will share the next details shortly.</p>${rows([["Destination", input.destination], ["Travel dates", `${input.travelStartDate} to ${input.travelEndDate}`]])}`), text: `Your custom trip ${input.name} is confirmed.` }); }
export async function sendEnquiryAdminNotification(input: EnquiryEmailInput) { const subject = `New JournAway ${input.type} enquiry from ${input.name}`; await sendAdmins(`enquiry:${input.id}:submitted:admin`, subject, shell(`New ${input.type} enquiry`, rows([["Customer", `${input.name} (${input.email})`], ["Phone", input.phone], ["Service", input.service], ["Destination", input.destination], ["Route", input.pickupLocation && input.dropoffLocation ? `${input.pickupLocation} to ${input.dropoffLocation}` : null], ["Travel dates", input.travelStartDate ? `${input.travelStartDate}${input.travelEndDate ? ` to ${input.travelEndDate}` : ""}` : null], ["Guests", input.guests ? String(input.guests) : null], ["Message", input.message]]) + `<p><a href="${siteUrl()}/admin/enquiries">Review enquiry</a></p>`), `New ${input.type} enquiry from ${input.name} (${input.email}).`, input.email); }
export async function sendAccessRequestAdminNotification(input: AccessAccount) { const label = input.role === "driver" ? "Driver" : "Hotel partner"; await sendAdmins(`access:${input.id}:requested:admin`, `New JournAway ${input.role} access request`, shell(`New ${label} access request`, rows([["Name", input.displayName], ["Email", input.email], ["Status", input.status], ["Reference", input.id], ["Submitted", input.createdAt]]) + `<p><a href="${siteUrl()}/admin/access">Review request</a></p>`), `New ${input.role} access request from ${input.displayName} (${input.email}).`, input.email); }
export async function sendAccessApprovedEmail(input: AccessAccount) { const label = input.role === "driver" ? "Driver Portal" : "Hotel Partner Portal"; const path = input.role === "driver" ? "/driver" : "/hotel"; const url = process.env[input.role === "driver" ? "DRIVER_PORTAL_URL" : "HOTEL_PARTNER_PORTAL_URL"] ?? `${siteUrl()}${path}`; await send({ eventKey: `access:${input.id}:approved:customer:${input.email}`, recipient: input.email, subject: `Your JournAway ${label} access has been approved`, html: shell("Portal access approved", `<p>Hello ${escapeHtml(input.displayName)},</p><p>Your request for access to the JournAway ${label} has been approved.</p><p><a href="${url}">Open ${label}</a></p><p>Sign in using your existing JournAway account.</p>`), text: `Your JournAway ${label} access has been approved. Open: ${url}` }); }
export async function sendEnquiryStatusUpdate(input: EnquiryEmailInput, previous: string) { if (input.status !== "in_progress" && input.status !== "closed" || previous === input.status) return; const statusText = input.status === "in_progress" ? "Our travel team is reviewing your request." : "Our travel team has completed its review of this request."; await send({ eventKey: `enquiry:${input.id}:status:${input.status}:customer:${input.email}`, recipient: input.email, subject: `Update on your JournAway ${input.type} enquiry`, html: shell("There’s an update on your enquiry", `<p>Hello ${escapeHtml(input.name)},</p><p>${escapeHtml(statusText)}</p>${rows([["Reference", input.id], ["New status", input.status.replace("_", " ")], ["Service", input.service], ["Route", input.pickupLocation && input.dropoffLocation ? `${input.pickupLocation} to ${input.dropoffLocation}` : null], ["Destination", input.destination]])}`), text: `Update on enquiry ${input.id}: ${input.status}. ${statusText}` }); }
